SET EXCLUSIVE OFF
SET MULTILOCKS ON
SET DELETED ON
SET REFRESH TO 5
SET REPROCESS TO 5 SECONDS
SET TALK OFF
SET CENTURY ON
SET DATE DMY
SET ANSI ON
SET ESCAPE OFF
SET NEAR OFF
SET NOTIFY ON
_SCREEN.minbutton = .T.
_SCREEN.maxbutton = .T.
_SCREEN.closable = .F.
CLOSE ALL
CLEAR ALL
DO FORM fab_sincosto_correo.SCX
READ EVENTS
CLOSE ALL
RELEASE ALL EXTENDED
SET SYSMENU TO DEFAULT
ENDPROC
